### ISSUE TITLE
While executing function it's returning location address

### ISSUE THREAD

**Issue by merbhushan** [mysqludf/lib_mysqludf_str#2]
My Mysql version is 5.7.14.
While I am executing SELECT lib_mysqludf_str_info() FROM DUAL; It's returning location address. For function calling it's returning the same thing. 
Below is a screenshot for the same.
![image](https://user-images.githubusercontent.com/25707262/28104328-1660ddb8-66f8-11e7-8036-6f6fb7c63a3c.png)

**Comment by merbhushan** [comment]
Sorry, It's not a location address but it's Hex value. I verify this online using Hex to Text converter.

**Comment by ghost** [comment]
I am not sure why the hex for "lib_mysqludf_str version 0.5" would be displayed instead of the string value. Maybe this is the default behavior of the GUI tool that you are using (what is that, by the way?). Maybe the GUI tool does not support inferring the return type of UDFs, or does not handle queries involving DUAL very well.

I re-checked the code for how we specify the return types of the UDFs, and it seems correct. E.g.:

```sql
create function lib_mysqludf_str_info returns string soname 'lib_mysqludf_str.so';
```

Because there does not appear to be a bug in lib_mysqludf_str, I am closing this issue. Please feel free to re-open if there is a bug in lib_mysqludf_str.

**Comment by merbhushan** [comment]
Thanks for your response. 
The issue is because of my GUI tool. It's showing me varchar binary string instead of text.
